### ISSUE TITLE
Calendar gets downloaded as an .ics instead of displayed

### ISSUE THREAD

**Issue by openmedi** [palfrey/beeminder-calendar#6] opened 2017-06-16 12:50 UTC
OS: 10.11.6

This happens in Chrome (Version 58.0.3029.110 (64-bit)) as well as in Safari (Version 10.1.1 (11603.2.5)). I figured out how to copy the link to the downloaded file by going to the downloads in safari right click on the .ics in the list and chose copy link.

P.S.: It is entirely possible that this app/service is simply dead but I thought I'd share the problem and the workaround.

**Comment by palfrey** [comment] 2017-06-16 21:01
It's alive, I just haven't done anything to it recently. This is a duplicate of the problem listed in #3

**Closed by palfrey** 2017-06-16 21:01 UTC
